### ISSUE TITLE
incorrect spacing in \printProofs when restating both the theorem and proof

### ISSUE THREAD

**Issue by szymonlopaciuk** [leo-colisson/proof-at-the-end#5]
When using the restate option the spacing between the theorem and its proof is larger that between the theorem and the preceding proof. It seems that page breaking is also encouraged between the theorem and its proof rather than before the theorem restatement.

**Comment by szymonlopaciuk** [comment]
When using the `restate` option the spacing between the theorem and its proof if larger that between the theorem and the preceding proof. It seems that page breaking is also encouraged between the theorem and its proof rather than before the theorem restatement.

**Comment by tobiasBora** [comment]
Thanks for your report, and sorry for the time I spent to answer. So I can confirm the bug, and the problem seems to be that `\label{...}` can sometimes add unwanted space.

Right now, the code is basically doing:
```
\prAtEndRestateii*
\label{proofsection:prAtEndii}\begin{proof}...\end{proof}
```
where `\prAtEndRestateii*` is the command to restate the theorem. The `\label` is necessary in order to allow me to get a label to the current section the code is located (it's quite dirty, but I can't find any better solution). What I can do maybe is to invert the `\label{}` and the `\prAtEndRestateii*` commands... but then it adds anyway a space between the previous proof and the current proof (I'm thinking that this same unwanted spacing may already be present for regular theorems). So I guess the best solution is to find out how to ensure that `\label` does not add more space... I tried to ask [here](https://tex.stackexchange.com/questions/600577/adding-a-label-between-two-proofs-adds-unwanted-space) how to do, I'm waiting for the answer.

**Comment by szymonlopaciuk** [comment]
Hi! No worries, and thanks for the reply!

I don't know the first thing about advanced latex stuff like this, otherwise maybe I would have attempted a fix myself. I'm not sure if I understand correctly, but if the space was to move between previous proof and the theorem restatement for the next one, that would be satisfying to me. Also, I am sure you have a reason to do this, but just in case, would moving the label inside the proof work?

**Comment by tobiasBora** [comment]
I can't move it inside the proof because I want to obtain the name of the current section, and if it's inside the proof I think to remember I get the proof number instead (and I already have another label inside the proof for that purpose). But I finally found a solution to remove all unwanted spaces thanks to [these comments](https://tex.stackexchange.com/questions/600577/adding-a-label-between-two-proofs-adds-unwanted-space). I just pushed the new version, feel free to test and let me know if it solves the issue. I'll close it meanwhile, we can reopen if it does not solve the problem for you.
